# based on https://github.com/dreamsofautonomy/zen-omp/blob/main/zen.toml
# modified color palette and executiontime style & padding

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[palette]
blue = "#57C7FF"
magenta = "#FF6AC1"
red = "#FF5C57"
yellow = "#F3F99D"
grey = "242"
cyan = "#9AEDFE"


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'p:blue'
template = '{{ .Path }}'
properties = { style = 'full' }

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:grey'
background = 'transparent'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
properties = { branch_icon = '', commit_icon = '@', fetch_status = true }


[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'p:yellow'
background = 'transparent'
template = '{{ .FormattedMs }} '
properties = { threshold = 5000, style = 'round' }


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:magenta{{end}}",
]
background = 'transparent'
template = '❯'


[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:magenta{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'p:magenta'
background = 'transparent'
template = '❯❯ '
