# add newline between prompts
add_newline = true

# prompt format
format = "$directory $git_branch$git_status\n$character"
right_format = "$cmd_duration"

# color palette
palette = "p10k"
[palettes.p10k]
blue = "#57C7FF"
magenta = "#FF6AC1"
red = "#FF5C57"
yellow = "#F3F99D"
grey = "242"
cyan = "#9AEDFE"

# prompt segments
[directory]
truncation_length = 9999
truncate_to_repo = false
format = "[$path](blue)"

[git_branch]
format = '[$branch](grey)'

[git_status]
format = "[$modified$staged](grey) [$ahead_behind](cyan)"
modified = "*"
staged = "*"

[character]
success_symbol = '[❯](magenta)'
error_symbol = '[❯](red)'

[cmd_duration]
min_time = 5000
format = "[$duration](yellow)"
